### PR TITLE
Add DaisyUI Theme called night to Tailwind Configuration

### PR DESCRIPTION
**Pull request by aedoardo1990**
I switched between different themes (e.g., "cupcake", "light", "forest") and ensured they are working correctly. After that I left only the "night" theme in the Tailwind Configuration file

### CODE REVIEW

**Review by lokytech5 — COMMENTED** [review]
nice

**Comment by lokytech5** [comment]
@aedoardo1990 thank you so much. there are some issues am yet to create, but I want to hear from you if you are familiar with some terms before I go ahead and create them.

**Comment by lokytech5** [comment]
have you work with the following, react query, zustand, zod, react-hook-form and @hookform/resolvers

**Comment by aedoardo1990** [comment]
@lokytech5 you are welcome :) I'll confirm you I have already worked with react query, zustand, zod, react-hook-form and @hookform/resolvers. I will be happy to help with issues related to them

**Comment by lokytech5** [comment]
Okay. i We go ahead with creating the issue and assign it to you

**Pull request merged**
