### PR TITLE
Set Up Axios API Client

### PR DESCRIPTION
**Pull request by aedoardo1990**

### CODE REVIEW

**Review by lokytech5 — COMMENTED** [review]
Good day @aedoardo1990, I think is better to create a dedicated Axios instance instead of using axios.defaults, as this approach ensures greater flexibility and encapsulation. Here is the implementation I suggest. 
``` bash
import axios from 'axios';

// Create the Axios instance
const apiClient = axios.create({
    baseURL: 'https://olikwzthj7.execute-api.us-east-1.amazonaws.com/dev',
    headers: {
        'Content-Type': 'application/json',
    },
    withCredentials: true, // Include credentials with requests
});

// Request interceptor
apiClient.interceptors.request.use(
    (config) => {
        const token = localStorage.getItem('token'); // Retrieve token from local storage
        if (token) {
            config.headers.Authorization = `Bearer ${token}`; // Add token to request headers
        }
        return config;
    },
    (error) => {
        return Promise.reject(error);
    }
);

// Response interceptor
apiClient.interceptors.response.use(
    (response) => {
        return response;
    },
    (error) => {
        if (error.response && error.response.status === 401) {
            // Handle 401 errors globally, e.g., redirect to login
            window.location.href = '/login';
        }
        return Promise.reject(error);
    }
);

export default apiClient;

```
Reason because we encapsulate the axios-client and also is flexible. Let me know if you have any questions about this.

**Comment by lokytech5** [comment]
looking forward to your reply

**Comment by aedoardo1990** [comment]
@lokytech5 thanks for all the detailed information and instructions! I like a lot your idea, it is cleaner and it should be easier to mantain and use throughout the application

**Comment by aedoardo1990** [comment]
@lokytech5 I have updated the branch aedoardo1990/e-get-why with the code you proposed

**Review by lokytech5 — APPROVED** [review]
am happy to hear that.

**Pull request merged**
